apiVersion: v1
kind: Secret
metadata:
  name: demo-crm-mongodb-uri
stringData:
  # https://www.mongodb.com/docs/manual/reference/connection-string/#standard-connection-string-format
  MONGODB_URI: "mongodb://root:yawiezel@mongo-mongodb-0.mongo-mongodb-headless,mongo-mongodb-1.mongo-mongodb-headless,mongo-mongodb-2.mongo-mongodb-headless:27017"
