version: "3"
services:
  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - my_network
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      # Add other environment variables for Flask app as needed

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - my_network
    environment:
      - discovery.type=single-node
      # Add security settings and other environment variables for Elasticsearch

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - flask-app
    networks:
      - my_network
    # Add security settings for Nginx

volumes:
  elasticsearch-data:

networks:
  my_network:
